### ISSUE TITLE
fix(jans-cli-tui) : add new asset  showing 500 error

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#9150]
**Describe the bug**

**To Reproduce**
1. install jans 
2. add new asset
3. add properties file in jans-auth

**Expected behavior**

should not get any error

**Screenshots**
![image](https://github.com/user-attachments/assets/38f57c2d-4c4c-4086-843d-054127fa3dc8)

**Desktop (please complete the following information):**
  - OS: suse 15 sp5
  - Version sp5
  - jans 1.1.4.nightly
  - DB opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by manojs1978** [comment]
@pujavs FYI

**Comment by pujavs** [comment]
Fixed via PR[9155](https://github.com/JanssenProject/jans/pull/9155)

**Comment by manojs1978** [comment]
@pujavs still facing issue for pgsql
![image](https://github.com/user-attachments/assets/41f13239-8987-4402-b002-f87592ca776e)
